roomfiles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rooms import urls as rooms_urls

from django.contrib.auth import views as auth_views
from users import views as user_views
from users.views import NotificationListView, register, profile

urlpatterns = [
    # Rooms Urls
    path('', include(rooms_urls)),

    path('admin/', admin.site.urls),

    # User Urls
    path('account/', include([
        path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

        path('profile/', user_views.profile, name='profile'),
        path('settings/', user_views.settings, name='user-settings'),

        path('password-reset/', auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            html_email_template_name="users/password_reset_email.html",
            subject_template_name="users/password_reset_subject.txt",
            extra_email_context={'site_name': 'RoomFiles'},
            ),
            name='password_reset'),

        path('password-reset/done/',
            auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
            name='password_reset_done'),

        path('password-reset/<uidb64>/<token>/confirm/',
            auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
            name='password_reset_confirm'),

        path('password-reset/complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
            name='password_reset_complete'),
    
        path('password-change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'), name='password_change'),
        path('password-change/success/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    
        path('close/', user_views.close_account_confirm, name='close-account')
    ])),
    

    
    # Notifications
    path('notifications/', include([
        # Notification ListView
        path('', NotificationListView.as_view(), name='notifications'),
        # Read all Notifications
        path('read/all/', user_views.api_read_all_notifications, name='api-notif-read-all'),
        
    ])),

    path('register/', user_views.register, name='register'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path, include

from . import views
from users import views as user_views
from .views import (
    RoomDetailView, RoomCreateView, RoomUpdateView, RoomListView,
    FileDetailView, FileCreateView, FileUpdateView, FileDeleteView,
    AnnouncementCreateView, AnnouncementUpdateView, AnnouncementDeleteView, AnnouncementListView,
    )

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('contact/success/', views.contact_success, name='contact_success'),
    

    # User Room Urls
    path('rooms/', RoomListView.as_view(template_name="rooms/user_rooms.html"), name="user-rooms"),
    path('room/create/', RoomCreateView.as_view(), name='room-create'),
    path('room/join/', views.join_room, name='room-join'),

    # Specific Room
    path('room/<int:room_pk>-<str:room_slug>/', include([

        path('', RoomDetailView.as_view(), name='room'),
        path('edit/', RoomUpdateView.as_view(), name='room-edit'),
        path('anns/', AnnouncementListView.as_view(), name='room-anns'),
        path('leave/', views.leave_room, name='room-leave'),

        
        # File Urls
        path('file/upload/', FileCreateView.as_view(), name='file-upload'),
        path('file/<int:file_pk>/', include([
            path('', FileDetailView.as_view(), name='file'),
            path('edit/', FileUpdateView.as_view(), name='file-edit'),
            path('delete/', FileDeleteView.as_view(), name='file-delete'),
        ])),


        # Announcement Urls
        path('ann/post/', AnnouncementCreateView.as_view(), name='ann-create'),
        path('ann/<int:ann_pk>/', include([
            path('edit/', AnnouncementUpdateView.as_view(), name='ann-edit'),
            path('delete/', AnnouncementDeleteView.as_view(), name='ann-delete'),
            
            path('api-like/', views.api_toggle_like, name='api-ann-like'),
        ])),
        
        # Read Announcement / File
        path('read/<str:model_type>/', user_views.api_read_objects, name='api-notif-read-objects'),
    ])),
    


]

users/models.py
from django.db import models
from django.db.models import Q
from django.http import JsonResponse

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import AbstractUser, UserManager
from django.conf import settings

from django.contrib.contenttypes.models import ContentType
from rooms.contenttypes import get_ann_contenttype, get_file_contenttype



class ActiveUserManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)

class User(AbstractUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    objects = UserManager()
    active = ActiveUserManager()

    def close_account(self):
        self.is_active = False
        self.save()

    class Meta:
        ordering = ['username']




class Avatar(models.Model):
    class Meta:
        ordering = ['name']
    
    name = models.CharField(max_length=30)
    image_url = models.URLField()

    def __str__(self):
        return f'{self.name} Avatar'




class ActiveProfileManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(user__is_active=True)

from django.contrib.postgres.fields import ArrayField
class Profile(models.Model):

    class Meta:
        ordering = ['user__username']

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)

    avatar = models.ForeignKey(Avatar, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    user_rooms = models.ManyToManyField('rooms.Room', related_name="user_rooms", blank=True)
    # user_rooms_bak = ArrayField(models.UUIDField(), blank=True, default=list)



    objects = ActiveProfileManager()

    def __str__(self):
        return f'{self.user.username} Profile'


    @property
    def display_username(self):
        return f'@{self.user.username}'

    @property
    def display_name(self):
        if self.first_name == '' and self.last_name == '': return 'Unnamed'
        return f'{self.first_name} {self.last_name}'
    

    # Notifications
    def get_unread_notifications(self):
        return Notification.objects.filter(
            target=self.user, 
            is_read=False,
        )

    @property
    def notification_count(self):
        return self.get_unread_notifications().count()

    def get_notification_count_in_room(self, room):
        unread_notifs = self.get_notifications_in_room(room)
        return unread_notifs.count()

    def get_notifications_in_room(self, room):
        unread_notifs = Notification.objects.filter(
            Q(rooms_file__room=room) | Q(rooms_announcement__room=room),
            is_read=False, target=self.user,
            content_type__in=[get_ann_contenttype(), get_file_contenttype()],
            )
        
        return unread_notifs

    def get_unread_files(self, room):
        unread_notifs = self.get_notifications_in_room(room)
        unread_files = unread_notifs.filter(content_type=get_file_contenttype())

        return unread_files
    
    def get_unread_anns(self, room):
        unread_notifs = self.get_notifications_in_room(room)
        unread_anns = unread_notifs.filter(content_type=get_ann_contenttype())
        return unread_anns

    # Read all notification of specific contenttype (announcement or file)
    def notifications_read_objects_of_type(self, room, model_type):
        user = self.user
        content_type = ContentType.objects.get_by_natural_key('rooms', model_type)

        content_notifs = self.get_notifications_in_room(room).filter(content_type=content_type)

        for notif in content_notifs:
            notif.read()
        
        response = {
            'done' : True,
            'unseen_object' : 0,
            'unseen_total' : self.notification_count
            }
        
        return response

    # Read all notification
    def notifications_read_all(self):
        user = self.user
        notifications = Notification.objects.filter(target=user, is_read=False)

        for notif in notifications:
            notif.read()

        notifications_count = Notification.objects.filter(target=user, is_read=False).count()

        response = { 'unseen_total': notifications_count }
        return response


    # Rooms
    def leave_room(self, room):
        self.user_rooms.remove(room)
        self.save()

    def join_room(self, room):
        self.user_rooms.add(room)
        self.save()



# Application-wide Notification
class Notification(models.Model):
    actor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='actor', on_delete=models.CASCADE)
    verb = models.CharField(max_length=50)
    target = models.ForeignKey(settings.AUTH_USER_MODEL,  related_name='target', on_delete=models.CASCADE)
    executed_datetime = models.DateTimeField(auto_now_add=True, editable=False)
    
    # Generic Foreign Key - so foreign model can be different models (eg. Announcement, File)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    action_obj = GenericForeignKey('content_type', 'object_id')

    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.actor.username} {self.verb}'

    def read(self):
        self.is_read = True
        self.save()

        return JsonResponse({ 'is_read' : True })

    class Meta:
        ordering = ['-executed_datetime']

users/forms.py
from users.models import User
from .models import Profile, Avatar

from django.contrib.auth.forms import UserCreationForm 
from django import forms



class UserRegisterForm(UserCreationForm):
    username = forms.CharField(min_length=8)
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileUpdateForm(forms.ModelForm):
    avatars = Avatar.objects.all()

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.apps import apps

from django.core.paginator import Paginator
from django.contrib.contenttypes.models import ContentType

from .forms import UserRegisterForm, ProfileUpdateForm
from django.views.generic import ListView

from .models import Avatar, Notification
from django.http import JsonResponse

# Rest Framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import permissions


# Views
def register(request):
    form = UserRegisterForm()

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()

            # Get username and display in messages
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created!')

            return redirect('login')

    return render(request, 'users/register.html', { 'form' : form })

@login_required
def profile(request):
    p_form = ProfileUpdateForm(instance=request.user.profile)

    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        avatar_id = request.POST.get('avatar')
        
        if p_form.is_valid():
            if (avatar_id != ''):
                avatar_id = int(avatar_id)
                request.user.profile.avatar = get_object_or_404(Avatar, pk=avatar_id)

            p_form.save()
            messages.success(request, 'Successfully updated your profile.')
            return redirect('profile')

    context = { 'p_form': p_form }
    return render(request, 'users/profile.html', context)

@login_required
def settings(request):
    return render(request, 'users/settings.html')

class NotificationListView(LoginRequiredMixin, ListView):
    model = Notification
    template_name = 'users/notification_list.html'
    context_object_name = 'notifications'
    
    def get_queryset(self):
        qs = Notification.objects.filter(target=self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        qs = self.get_queryset()

        # Paginate
        paginator = Paginator(qs, 10)
        page_number = self.request.GET.get('page', 1) # Gets page parameter on Ajax / Fetch calls
        page_obj = paginator.get_page(page_number)
        context['notifications'] = page_obj

        return context

@login_required
def close_account_confirm(request):
    if request.POST:
        if 'close-account' in request.POST:
            return close_account_done(request)

    return render(request, 'users/close_account.html')

def close_account_done(request):
    request.user.close_account()
    return render(request, 'users/close_account_done.html')
    


# AJAX Calls

# Read File or Announcement Notification
@api_view(['PUT'])
def api_read_objects(request, room_pk, room_slug, model_type):
    if request.method == 'PUT':
        room = get_object_or_404(apps.get_model('rooms', 'Room'), pk=room_pk)
        response = request.user.profile.notifications_read_objects_of_type(room, model_type)
        if response:
            return Response(response, status=status.HTTP_200_OK)

# Read all notifications
@api_view(['PUT'])
def api_read_all_notifications(request):
    if request.method == 'PUT':
        response = request.user.profile.notifications_read_all()
        if response:
            return Response(response, status=status.HTTP_200_OK)

users/templates/users/close_account.html
{% extends 'rooms/base.html' %}

{% block html_title %} - Close Account{% endblock %}
{% block meta_desc %}Close your RoomFiles account.{% endblock %}

{% block content %}
<div class="container">
    <div class="card mt-3">
        <div class="card-body">
            <div class="card-header">
                <h3 class="text-danger">Close Account</h3>
            </div>

            <div class="container pt-3">
                <p><strong>Are you sure you want to close your account?</strong></p>
                
                <p>This action cannot be undone, and you cannot log in with this account again.</p>
            </div>

            <form method="POST" class="pt-4">
                {% csrf_token %}
                <button id='closeAccount' name="close-account" type="submit" class="btn btn-block btn-raised btn-danger text-lowercase" disabled>
                    I understand, close my account
                    <span class="countdown text-lowercase" data-duration="10"></span>
                </button>
            </form>
            
        </div>
    </div>
    
</div>
{% endblock content %}

users/templates/users/close_account_done.html
{% extends 'rooms/base.html' %}

{% block content %}
<div class="container">
    <div class="card mt-3">
        <div class="card-body">
            <div class="card-header">
                <h3>Closed Account</h3>
            </div>

            <div class="container pt-3">
                <p>You have closed your account.</p>
            </div>
        </div>
    </div>
    
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'rooms/base.html' %}

{% block html_title %} - Login{% endblock %}
{% block meta_desc %}Login with your RoomFiles account. Gather with your friends and collaborate with RoomFiles.{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        <div class="card-body">

            <form method="POST">
                {% csrf_token %}
                <legend>Login</legend>
                <fieldset class="form-group">
                    {{ form | crispy }}
                </fieldset>

                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">
                        Login
                    </button>
                </div>

                <div class="text-center small">
                    <p>Don't have an account? <a href="{% url 'register' %}">Sign Up</a></p>
                    <p><a href="{% url 'password_reset' %}">Forgot password?</a></p>
                </div>

            </form>

        </div>
    </div>

</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'rooms/base.html' %}

{% block content %}
    <div class="container">

        <div class="card">


            <div class="card-body">

                <div class="card-header">
                    <h5>You have been logged out.</h5>
                </div>
    
                <div class="container text-muted pt-3">
                    <a href="{% url 'login' %}" class="card-link small">Log in Again</a>
                    <span> | </span>
                    <a href="{% url 'home' %}" class="card-link small">Back to Home</a>
                </div>
                
            </div>

        </div>
    </div>
{% endblock content %}

users/templates/users/notification_list.html
{% extends 'rooms/base.html' %}
{% block html_title %} - Notifications{% endblock %}

{% load static %}

{% block content %}
<div class="container infinite-container">

    <div class="text-right py-3">
        <a href="{% url 'api-notif-read-all' %}" class="btn btn-secondary btn-sm btn-raised" id="readAllNotifications">Mark all as read</a>
    </div>

    {% for notif in notifications %}
    <a href="{{ notif.action_obj.get_absolute_url }}" class="card infinite-item mb-3 {% if not notif.is_read %}card-unread{% endif %}">
        <div class="card-body">

            {% if notif.actor.profile.avatar %}
                <img src="{{request.scheme}}://{{request.get_host}}{{ notif.actor.profile.avatar.image_url }}" alt="{{notif.actor.profile.avatar.name}}" class="avatar-thumbnail float-left">
            {% else %}
                <img src="{% static 'images/user-default.svg' %}" alt="Default Profile Icon" class="avatar-thumbnail float-left">
            {% endif %}


            <div class="content-with-avatar">
                <div class="text-truncated">
                    <strong>{{ notif.actor.profile.display_username }}</strong>
                    
                    {{ notif.verb }}

                    <!-- a or an -->
                    {% if notif.content_type.name|slice:':1' in 'aeiou' %} an {% else %} a {% endif %}

                    {{ notif.content_type.name }}

                    {{ notif.action_obj.notification_text }}

                </div>

                <span class="small d-block text-muted pt-2">
                    {{ notif.executed_datetime|timesince }}
                </span>
            </div>
        </div>
    </a>
    {% endfor %}

</div>

{% if notifications.has_next %}
    <a href="?page={{ notifications.next_page_number }}" class="infinite-more-link"></a>
{% else %}
    <div class="text-center infinite-item pt-2 pb-4">
        No more notifications
    </div>
{% endif %}

{% endblock content %}

users/templates/users/password_change_done.html
{% extends 'rooms/base.html' %}

{% block content %}
<div class="container">
    <div class="card mt-3">
        <div class="card-body">
            <div class="card-header">
                <h3>Password Changed!</h3>
            </div>
            <div class="card-body">
                You have successfully changed your password. <a href="{% url 'user-settings' %}">Back to Settings</a>.
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_change_form.html
{% extends 'rooms/base.html' %}

{% block html_title %} - Change Password{% endblock %}
{% block meta_desc %}Change your password. Gather with your friends and collaborate with RoomFiles.{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        <div class="card-body">

            <form method="POST">
                {% csrf_token %}
                <legend>Change Your Password</legend>
                <fieldset class="form-group mt-3">
                    {{ form | crispy }}
                </fieldset>

                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">
                        Save New Password
                    </button>
                </div>

            </form>

        </div>
    </div>

</div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'rooms/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        <div class="card-body">

            <form method="POST">
                {% csrf_token %}
                <legend>Reset Your Password</legend>
                <fieldset class="form-group mt-3">
                    {{ form | crispy }}
                </fieldset>

                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">
                        Reset
                    </button>
                </div>

            </form>

        </div>
    </div>

</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'rooms/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        
        <div class="card-body">
            <div class="card-header">
                <h3 class="card-title font-weight-bold">Look at your mail!</h3>
            </div>

            <div class="container pt-3">
                <p>We sent you an email containing the next steps to reset your password.</p>
            </div>
            
        </div>
    </div>

</div>
{% endblock content %}

users/templates/users/password_reset_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml">
  <head>
    <title>{{ site_name }} Password Reset</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0 " />

  </head>

  <body style="font-family: 'Roboto','Helvetica','Arial',sans-serif;">
        {% url 'password_reset_confirm' uidb64=uid token=token as reset_end_url %}
        {% with reset_url=protocol|add:'://'|add:domain|add:reset_end_url %}

        <h1>{{ site_name }} Password Reset</h1>
      
        <hr>

        <p>You're receiving this email because you requested a password reset for your user account at {{ site_name }}.</p>
        <p>Please click the button below to reset your password:</p>
        <p style="text-align: center;">
            <a href="{{ reset_url }}" style="
                text-decoration: none !important;
                background-color: #3f51b5 !important;
                color: #fff !important;
                padding: 1em !important;
                border-radius: 5px !important;
                display: inline-block !important;">
                Reset your password
            </a>
        </p>

        <small>
            or click this link instead: 
            <a href="{{ reset_url }}"
            style="text-decoration: none !important;">
                {{reset_url}}</a>
        </small>

        <p>Your username, in case you’ve forgotten: {{ user.username }}</p>
        <hr>
        <p>Thanks for using <a href="">{{ site_name }}</a>!</p>
            
      {% endwith %}

      
  </body>
</html>

users/templates/users/password_reset_form.html
{% extends 'rooms/base.html' %}
{% block html_title %} - Reset Password{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        <div class="card-body">

            <form method="POST">
                {% csrf_token %}
                <legend>Reset Your Password</legend>
                <p>Please enter the email address used in your account.</p>
                <fieldset class="form-group mt-3">
                    {{ form | crispy }}
                </fieldset>

                <small>
                    <strong class="text-warning">NOTE: </strong>
                    If you haven't entered your email address upon registration, you <strong>cannot</strong> receive an email password reset.
                </small>

                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">
                        Reset
                    </button>
                </div>

            </form>

        </div>
    </div>

</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'rooms/base.html' %}

{% block html_title %} - {{ user.profile.display_username }}{% endblock %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}


<div class="container">

    
    <div class="card mt-3">
        <div class="card-body">

            <!-- HEADER -->
            <div class="card-header">

                <div class="row">
                    <div class="col-12 col-sm-auto">
                        <div class="avatar-container mx-auto"
                        {% if user.is_staff %}
                        data-border="{% static 'images/special-border.png' %}"
                        {% endif %}
                        >

                        {% if p_form.instance.avatar %}
                            <img src="{{request.scheme}}://{{request.get_host}}{{ p_form.instance.avatar.image_url }}" class="avatar-preview">
                        {% else %}
                            <img src="{% static 'images/user-default.svg' %}" alt="Default Profile Icon" class="avatar-preview">
                        {% endif %}
                        </div>

                    </div>

                    <div class="col-12 col-sm d-flex align-items-center justify-content-center justify-content-sm-start">
                        <!-- User Information -->
                        <div class="text-center text-sm-left py-3">
                            
                            <h5 {%if user.profile.display_name == 'Unnamed'%}class="text-danger"{% endif %}>
                                {{ user.profile.display_name }}
                            </h5>

                            <h6>{{ user.profile.display_username }}</h6>
                            
                            <small>
                                {% if user.email %} {{ user.email }} {% else %} No email {% endif %}
                            </small>
                        </div>
                    </div>
                </div>

                


                
            </div>

            <div class="container pt-4">
                
                <!-- PROFILE INFO -->
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend>Your Profile</legend>
                        
                        {{ p_form | crispy }}

                        <!-- Custom Avatar Preview -->
                        <div class="form-group bmd-form-group">
                            <input type="hidden" name="avatar" id="id_avatar" value="{{ p_form.instance.avatar.id }}">

                            <label for="id_avatar" class="bmd-label-static">Avatar</label>
                            
                            <!-- Avatar Custom Select Input -->
                            <div class="pt-3">
                                {% include 'users/avatar-input/avatar_modal_select.html' %}
                            </div>
                            

                        </div>

                    </fieldset>
                    <button class="btn btn-primary btn-raised btn-block" type="submit">
                        Save Profile Changes
                    </button>
                </form>

                <!-- ACCOUNT SETTINGS -->
                <a href="{% url 'user-settings' %}" class="btn btn-sm btn-secondary btn-block" type="submit">
                    Account Settings...
                </a>
                
            </div>

        </div>

    </div>

</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'rooms/base.html' %}

{% block html_title %} - Sign Up{% endblock %}
{% block meta_desc %}Join RoomFiles now! Gather with your friends and collaborate with RoomFiles.{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        <div class="card-body">

            <form method="POST">
                {% csrf_token %}
                <legend>Sign Up</legend>
                <fieldset class="form-group">
                    {{ form | crispy }}
                </fieldset>

                <div class="form-group text-center">
                    <button class="btn btn-primary" type="submit">
                        Register
                    </button>
                </div>

                <div class="text-center small">
                    <p>Already have an account? <a href="{% url 'login' %}">Log in</a></p>
                </div>
            </form>

        </div>
    </div>

</div>
{% endblock content %}

users/templates/users/settings.html
{% extends 'rooms/base.html' %}

{% block html_title %} - Account Settings{% endblock %}

{% block content %}
<div class="container">

    <div class="card mt-3">
        <div class="card-body">

            <h4>Account Settings</h4>

            <a href="{% url 'password_change' %}" class="btn btn-secondary btn-block btn-raised mt-4 p-2">
                <span class="material-icons float-left">lock</span>                
                Change Password
            </a>

            <a href="{% url 'close-account' %}" class="btn btn-danger btn-block mt-4">
                <span class="material-icons float-left">delete_forever</span>
                Close Account
            </a>

        </div>
    </div>

</div>
{% endblock content %}